<ProcessingScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: "16dp"
        spacing: "16dp"

        MDLabel:
            text: "Procesamiento de Imágenes"
            halign: "center"
            font_style: "H5"

        MDProgressBar:
            value: root.progress
            max: 100

        MDRaisedButton:
            text: "Iniciar Procesamiento"
            on_release: root.start_processing()
            pos_hint: {"center_x": .5}